apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-canary
  labels:
    app: nginx-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hello
  template:
    metadata:
      labels:
        app: nginx-hello
        env: canary
    spec:
      containers:
      - name: nginx-hello
        image: harbor.haas-424.pez.pivotal.io/demo/nginx-hello:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          # You must specify requests for CPU to autoscale
          # based on CPU utilization
          limits:
            cpu: "200m"
          requests:
            cpu: "200m"
      imagePullSecrets:
      - name: harbor-secret
